import io
import json
import shutil
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path

from tools import learning, learning_map, project_lifecycle, project_store, runtime


REPO_ROOT = Path(__file__).resolve().parents[1]


class LearningMapTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        (self.root / "templates").mkdir()
        for name in ("MISSION.md", "LEARNER.md", "ROADMAP.md", "STATE.md"):
            shutil.copy2(REPO_ROOT / "templates" / name, self.root / "templates" / name)

    def tearDown(self):
        self.tmp.cleanup()

    def create(self, project_id="bayes"):
        return project_lifecycle.create_project(
            self.root,
            title="Bayes from first principles" if project_id == "bayes" else "Rust ownership",
            goal="Explain and apply the target mechanism independently",
            project_id=project_id,
        )

    def evidence(self):
        decision = runtime.list_receipts(self.root, "decision")[-1]
        runtime.record_learner_response(
            self.root,
            decision["id"],
            "I compare the prior populations before conditioning.",
        )
        result = runtime.advance_learning_turn(
            self.root,
            decision["id"],
            {
                "assessment": {
                    "level": "explanation",
                    "outcome": "supports",
                    "result_summary": "The learner used both conditioned populations.",
                    "scaffolding": "light",
                    "context": "same",
                    "delay": "immediate",
                    "independence": "same_form",
                    "supports": ["base-rate comparison"],
                    "contradicts": [],
                    "confidence": "medium",
                    "assessor": "test-suite",
                },
                "next_decision": {
                    "mode": "teach",
                    "target": "Bayes reasoning",
                    "concept_ids": ["bayes-reasoning"],
                    "frontier_hypothesis": "A context switch can test cue dependence.",
                    "uncertainty": "medium",
                    "move": "transfer",
                    "rationale": "Change context while preserving structure.",
                    "learner_action": "Explain a non-medical example.",
                    "representation": {
                        "kind": "conversation",
                        "purpose": "Test independent reconstruction.",
                    },
                    "expected_evidence": "Correct conditional direction.",
                    "falsification_signal": "The conditional is reversed.",
                },
            },
        )
        return result["evidence"]["id"]

    def payload(self, evidence_id):
        return {
            "rationale": "The first response exposed base-rate comparison as the nearest frontier.",
            "evidence_ids": [evidence_id],
            "frontier": ["bayes-reasoning"],
            "nodes": [
                {
                    "id": "conditional-probability",
                    "label": "Conditional probability",
                    "kind": "concept",
                    "mission_relevance": "supporting",
                },
                {
                    "id": "bayes-reasoning",
                    "label": "Bayes reasoning",
                    "kind": "strategy",
                    "mission_relevance": "core",
                },
            ],
            "edges": [
                {
                    "id": "conditional-to-bayes",
                    "source": "conditional-probability",
                    "target": "bayes-reasoning",
                    "relation": "prerequisite",
                    "confidence": "high",
                }
            ],
        }

    def test_new_project_starts_with_honest_empty_revision(self):
        self.create()
        context = project_store.resolve_project_context(self.root)
        value = learning_map.load_learning_map(self.root)

        self.assertEqual(value["revision"], 0)
        self.assertEqual(value["project_id"], "bayes")
        self.assertEqual(value["nodes"], [])
        self.assertEqual(value["frontier"], [])
        self.assertTrue(context.learning_map_path.is_file())
        self.assertTrue((context.learning_map_path.parent / "revisions" / "000000.json").is_file())
        projection = context.roadmap_markdown_path.read_text(encoding="utf-8")
        self.assertIn("Revision: **0**", projection)
        self.assertIn("Do not edit this file directly", projection)

    def test_published_schema_excludes_mastery_and_layout(self):
        schema = json.loads(
            (REPO_ROOT / "schemas" / "learning-map-v0.1.json").read_text(encoding="utf-8")
        )
        node = schema["$defs"]["node"]
        self.assertEqual(node["properties"]["kind"]["enum"], [
            "concept", "procedure", "strategy",
        ])
        self.assertNotIn("state", node["properties"])
        self.assertNotIn("position", node["properties"])
        self.assertNotIn("layout", schema["properties"])

    def test_revision_separates_topology_from_runtime_mastery(self):
        self.create()
        evidence_id = self.evidence()

        value = learning_map.update_learning_map(self.root, self.payload(evidence_id))

        self.assertEqual(value["revision"], 1)
        self.assertEqual(value["parent_revision"], 0)
        self.assertEqual(value["delta"]["added_node_ids"], [
            "bayes-reasoning",
            "conditional-probability",
        ])
        self.assertEqual(value["delta"]["added_edge_ids"], ["conditional-to-bayes"])
        self.assertTrue(value["delta"]["frontier_changed"])
        self.assertNotIn("state", value["nodes"][0])
        projection = project_store.resolve_project_context(self.root).roadmap_markdown_path.read_text(encoding="utf-8")
        self.assertIn("`conditional-probability`", projection)
        self.assertIn("prerequisite", projection)
        state_path = project_store.resolve_project_context(self.root).runtime_root / "state.json"
        state = json.loads(state_path.read_text(encoding="utf-8"))
        self.assertEqual(state["concepts"], {})

    def test_second_revision_records_structural_delta_without_overwriting_history(self):
        self.create()
        evidence_id = self.evidence()
        first = learning_map.update_learning_map(self.root, self.payload(evidence_id))
        update = self.payload(evidence_id)
        update["nodes"].append({
            "id": "novel-transfer",
            "label": "Novel-context transfer",
            "kind": "procedure",
            "mission_relevance": "core",
        })
        update["edges"].append({
            "id": "bayes-to-transfer",
            "source": "bayes-reasoning",
            "target": "novel-transfer",
            "relation": "transfer",
            "confidence": "medium",
        })
        update["frontier"] = ["novel-transfer"]

        second = learning_map.update_learning_map(self.root, update)

        self.assertEqual(second["revision"], 2)
        self.assertEqual(second["delta"]["added_node_ids"], ["novel-transfer"])
        self.assertEqual(second["delta"]["added_edge_ids"], ["bayes-to-transfer"])
        revision = project_store.resolve_project_context(self.root).learning_map_path.parent / "revisions" / "000001.json"
        self.assertEqual(json.loads(revision.read_text(encoding="utf-8")), first)

    def test_rejects_mastery_fields_and_invalid_edges(self):
        self.create()
        evidence_id = self.evidence()
        with_state = self.payload(evidence_id)
        with_state["nodes"][0]["state"] = "stable"
        with self.assertRaisesRegex(learning_map.LearningMapError, "unsupported state"):
            learning_map.update_learning_map(self.root, with_state)

        invalid_edge = self.payload(evidence_id)
        invalid_edge["edges"][0]["source"] = "missing-node"
        with self.assertRaisesRegex(learning_map.LearningMapError, "reference a node"):
            learning_map.update_learning_map(self.root, invalid_edge)

    def test_rejects_noop_and_nonempty_revision_zero(self):
        self.create()
        evidence_id = self.evidence()
        payload = self.payload(evidence_id)
        learning_map.update_learning_map(self.root, payload)
        with self.assertRaisesRegex(learning_map.LearningMapError, "does not change"):
            learning_map.update_learning_map(self.root, payload)

        forged = learning_map._empty_map("bayes", "2026-09-16T00:00:00Z")
        forged["nodes"] = payload["nodes"]
        with self.assertRaisesRegex(learning_map.LearningMapError, "honest empty"):
            learning_map.validate_learning_map(forged, "bayes")

    def test_rejects_cross_project_evidence_and_read_only_projects(self):
        self.create()
        evidence_id = self.evidence()
        self.create("rust")
        with self.assertRaisesRegex(learning_map.LearningMapError, "cannot read evidence"):
            learning_map.update_learning_map(self.root, self.payload(evidence_id))

        rust_evidence = self.evidence()
        project_lifecycle.pause_project(self.root, "rust")
        with self.assertRaisesRegex(learning_map.LearningMapError, "paused Project"):
            learning_map.update_learning_map(self.root, self.payload(rust_evidence))

    def test_cli_updates_and_reads_canonical_map(self):
        self.create()
        evidence_id = self.evidence()
        payload = self.root / "map.json"
        payload.write_text(json.dumps(self.payload(evidence_id)), encoding="utf-8")
        output = io.StringIO()
        with redirect_stdout(output):
            result = learning.main(["map-update", str(payload)], repo_root=self.root)
        self.assertEqual(result, 0)
        self.assertEqual(json.loads(output.getvalue())["revision"], 1)

        output = io.StringIO()
        with redirect_stdout(output):
            result = learning.main(["map"], repo_root=self.root)
        self.assertEqual(result, 0)
        self.assertEqual(json.loads(output.getvalue())["frontier"], ["bayes-reasoning"])


if __name__ == "__main__":
    unittest.main()
